name: Update Formula

on:
  repository_dispatch:
    types: [formula-update]

permissions:
  contents: write
  pull-requests: write

jobs:
  update-formula:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update formula
        run: |
          VERSION="${{ github.event.client_payload.version }}"
          SHA256_DARWIN_ARM64="${{ github.event.client_payload.sha256_darwin_arm64 }}"
          SHA256_DARWIN_X64="${{ github.event.client_payload.sha256_darwin_x64 }}"
          SHA256_LINUX_ARM64="${{ github.event.client_payload.sha256_linux_arm64 }}"
          SHA256_LINUX_X64="${{ github.event.client_payload.sha256_linux_x64 }}"

          # Strip 'v' prefix from version for the version field
          VERSION_WITHOUT_V="${VERSION#v}"

          # Update version (without 'v' prefix)
          sed -i "s/version \".*\"/version \"$VERSION_WITHOUT_V\"/" jira-cli-mcp.rb

          # Update URLs (with 'v' prefix) - handle both 'v' and 'vv' cases
          sed -i "s|download/v\{1,2\}[0-9.]*|download/$VERSION|g" jira-cli-mcp.rb

          # Update SHA256 values - handle both real hashes and PLACEHOLDER_* values
          sed -i "s/sha256 \"[^\"]*\" # darwin-arm64/sha256 \"$SHA256_DARWIN_ARM64\" # darwin-arm64/" jira-cli-mcp.rb
          sed -i "s/sha256 \"[^\"]*\" # darwin-x64/sha256 \"$SHA256_DARWIN_X64\" # darwin-x64/" jira-cli-mcp.rb
          sed -i "s/sha256 \"[^\"]*\" # linux-arm64/sha256 \"$SHA256_LINUX_ARM64\" # linux-arm64/" jira-cli-mcp.rb
          sed -i "s/sha256 \"[^\"]*\" # linux-x64/sha256 \"$SHA256_LINUX_X64\" # linux-x64/" jira-cli-mcp.rb

      - name: Test formula syntax
        run: |
          # Basic Ruby syntax check
          ruby -c jira-cli-mcp.rb

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update formula to ${{ github.event.client_payload.version }}"
          title: "Update formula to ${{ github.event.client_payload.version }}"
          body: |
            Automated update from jira-cli-mcp release ${{ github.event.client_payload.version }}

            ## SHA256 Checksums
            - darwin-arm64: `${{ github.event.client_payload.sha256_darwin_arm64 }}`
            - darwin-x64: `${{ github.event.client_payload.sha256_darwin_x64 }}`
            - linux-arm64: `${{ github.event.client_payload.sha256_linux_arm64 }}`
            - linux-x64: `${{ github.event.client_payload.sha256_linux_x64 }}`

            ## Release Notes
            See: https://github.com/choplin/jira-cli-mcp/releases/tag/${{ github.event.client_payload.version }}
          branch: update-${{ github.event.client_payload.version }}
          delete-branch: true

